version: '3.5'

services:
    master:
        build: .
        container_name: master
        command:
            - roscore

    turtle_node:
        build: .
        container_name: turtle_node 
        environment:
            ROS_HOSTNAME: turtle_node
            ROS_MASTER_URI: http://master:11311
            DISPLAY: 
        volumes:
            - /tmp/.X11-unix:/tmp/.X11-unix
        command: rosrun turtlesim turtlesim_node 
        depends_on: 
            - master

    turtle_teleop_key:
        build: .
        container_name: turtle_teleop_key
        environment:
            ROS_HOSTNAME: turtle_teleop_key
            ROS_MASTER_URI: http://master:11311
        command: rosrun turtlesim turtle_teleop_key
        depends_on: 
            - master
